In [342]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [38]:
mvp = pd.read_csv ("mvps_table.csv")
mvp

,Unnamed: 0,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,...,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48,Year
0,0,1,Michael Jordan,27,CHI,77.0,891.0,960,0.928,82,...,6.0,5.5,2.7,1.0,0.539,0.312,0.851,20.3,0.321,1991
1,1,2,Magic Johnson,31,LAL,10.0,497.0,960,0.518,79,...,7.0,12.5,1.3,0.2,0.477,0.320,0.906,15.4,0.251,1991
2,2,3,David Robinson,25,SAS,6.0,476.0,960,0.496,82,...,13.0,2.5,1.5,3.9,0.552,0.143,0.762,17.0,0.264,1991
3,3,4,Charles Barkley,27,PHI,2.0,222.0,960,0.231,67,...,10.1,4.2,1.6,0.5,0.570,0.284,0.722,13.4,0.258,1991
4,4,5,Karl Malone,27,UTA,0.0,142.0,960,0.148,82,...,11.8,3.3,1.1,1.0,0.527,0.286,0.770,15.5,0.225,1991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
481,7,8,Stephen Curry,33,GSW,0.0,4.0,1000,0.004,64,...,5.2,6.3,1.3,0.4,0.437,0.380,0.923,8.0,0.173,2022
482,8,9,Chris Paul,36,PHO,0.0,2.0,1000,0.002,65,...,4.4,10.8,1.9,0.3,0.493,0.317,0.837,9.4,0.210,2022
483,9,10T,DeMar DeRozan,32,CHI,0.0,1.0,1000,0.001,76,...,5.2,4.9,0.9,0.3,0.504,0.352,0.877,8.8,0.154,2022
484,10,10T,Kevin Durant,33,BRK,0.0,1.0,1000,0.001,55,...,7.4,6.4,0.9,0.9,0.518,0.383,0.910,8.4,0.198,2022
485,11,10T,LeBron James,37,LAL,0.0,1.0,1000,0.001,56,...,8.2,6.2,1.3,1.1,0.524,0.359,0.756,7.5,0.172,2022

In [44]:
mvp.columns

Index(['Unnamed: 0', 'Rank', 'Player', 'Age', 'Tm', 'First', 'Pts Won',
       'Pts Max', 'Share', 'G', 'MP', 'PTS', 'TRB', 'AST', 'STL', 'BLK', 'FG%',
       '3P%', 'FT%', 'WS', 'WS/48', 'Year'],
      dtype='object')

In [103]:
mvp.drop(mvp[mvp["Year"] == 1991].index, inplace = True)

In [104]:
mvp = mvp[['Player', 'Year','Pts Won', 'Pts Max', 'Share']]

In [105]:
mvp

             Player  Year  Pts Won  Pts Max  Share
20   Michael Jordan  1992    900.0      960  0.938
21    Clyde Drexler  1992    561.0      960  0.584
22   David Robinson  1992    337.0      960  0.351
23      Karl Malone  1992    262.0      960  0.273
24    Patrick Ewing  1992    100.0      960  0.104
..              ...   ...      ...      ...    ...
481   Stephen Curry  2022      4.0     1000  0.004
482      Chris Paul  2022      2.0     1000  0.002
483   DeMar DeRozan  2022      1.0     1000  0.001
484    Kevin Durant  2022      1.0     1000  0.001
485    LeBron James  2022      1.0     1000  0.001

[466 rows x 5 columns]

In [56]:
mvp.dtypes

Player      object
Year         int64
Pts Won    float64
Pts Max      int64
Share      float64
dtype: object

In [61]:
players = pd.read_csv("players.csv")
players

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
0,1,Alaa Abdelnaby,PF,22,POR,43,0,6.7,1.3,2.7,...,0.6,1.4,2.1,0.3,0.1,0.3,0.5,0.9,3.1,1992
1,2,Mahmoud Abdul-Rauf,PG,21,DEN,67,19,22.5,6.2,15.1,...,0.5,1.3,1.8,3.1,0.8,0.1,1.6,2.2,14.1,1992
2,3,Mark Acres,C,28,ORL,68,0,19.3,1.6,3.1,...,2.1,3.2,5.3,0.4,0.4,0.4,0.6,3.2,4.2,1992
3,4,Michael Adams,PG,28,DEN,66,66,35.5,8.5,21.5,...,0.9,3.0,3.9,10.5,2.2,0.1,3.6,2.5,26.5,1992
4,5,Mark Aguirre,SF,31,DET,78,13,25.7,5.4,11.7,...,1.7,3.1,4.8,1.8,0.6,0.3,1.6,2.7,14.2,1992
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18435,601,Thaddeus Young,PF,33,TOR,26,0,18.3,2.6,5.5,...,1.5,2.9,4.4,1.7,1.2,0.4,0.8,1.7,6.3,2022
18436,602,Trae Young,PG,23,ATL,76,76,34.9,9.4,20.3,...,0.7,3.1,3.7,9.7,0.9,0.1,4.0,1.7,28.4,2022
18437,603,Omer Yurtseven,C,23,MIA,56,12,12.6,2.3,4.4,...,1.5,3.7,5.3,0.9,0.3,0.4,0.7,1.5,5.3,2022
18438,604,Cody Zeller,C,29,POR,27,0,13.1,1.9,3.3,...,1.9,2.8,4.6,0.8,0.3,0.2,0.7,2.1,5.2,2022
18439,605,Ivica Zubac,C,24,LAC,76,76,24.4,4.1,6.5,...,2.9,5.6,8.5,1.6,0.5,1.0,1.5,2.7,10.3,2022

In [52]:
c = players.columns
d = mvp.columns

In [45]:
#cross-checking for similar columns
def check_the_columns(players, mvps):
    PC = players.columns
    MC = mvps.columns
    for c in PC:
        if c in [d for d in MC]: 
            print (c)
        else:
            pass



def find_common_columns(df1, df2):
    common_columns = set(df1.columns) & set(df2.columns)
    return common_columns

In [ ]:
check_the_columns(players, mvp)

In [66]:
del players["Rk"]

In [317]:
players['Player'] = players['Player'].str.replace('*', '', regex=False)

In [318]:
players.head(20)

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
165,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,.476,...,2.5,3.8,6.3,0.9,0.7,0.3,1.2,1.4,9.1,1992.0
618,A.C. Green,PF,29,LAL,82,55,34.4,4.6,8.6,.537,...,3.5,5.2,8.7,1.4,1.1,0.5,1.4,1.8,12.8,1993.0
1106,A.C. Green,PF,30,PHO,82,55,34.5,5.7,11.3,.502,...,3.4,5.8,9.2,1.7,0.9,0.5,1.2,1.7,14.7,1994.0
1595,A.C. Green,SF,31,PHO,82,52,32.8,3.8,7.5,.504,...,2.4,5.8,8.2,1.5,0.7,0.4,1.4,1.8,11.2,1995.0
2092,A.C. Green,SF,32,PHO,82,36,25.8,2.6,5.4,.484,...,2.0,4.7,6.8,0.9,0.5,0.3,1.0,1.7,7.5,1996.0
2668,A.C. Green,PF,33,NaN,83,73,30.0,2.8,5.8,.483,...,2.7,5.2,7.9,0.8,0.8,0.2,0.9,1.7,7.2,1997.0
3256,A.C. Green,PF,34,DAL,82,68,32.3,3.0,6.5,.453,...,2.7,5.5,8.1,1.5,1.0,0.3,0.8,1.9,7.3,1998.0
3815,A.C. Green,PF,35,DAL,50,35,18.5,2.2,5.1,.422,...,1.6,2.9,4.6,0.5,0.6,0.2,0.4,1.4,4.9,1999.0
4344,A.C. Green,PF,36,LAL,82,82,23.5,2.1,4.7,.447,...,2.0,4.0,5.9,1.0,0.6,0.2,0.6,1.5,5.0,2000.0
4864,A.C. Green,PF,37,MIA,82,1,17.2,1.8,4.0,.444,...,1.3,2.5,3.8,0.5,0.4,0.1,0.5,1.5,4.5,2001.0
4217,A.J. Bramlett,C,23,CLE,8,0,7.6,0.5,2.6,.190,...,1.5,1.3,2.8,0.0,0.1,0.0,0.4,1.6,1.0,2000.0
128,A.J. English,SG,23,WSB,70,12,20.6,3.6,8.2,.439,...,0.9,1.2,2.1,2.5,0.4,0.2,1.6,1.8,8.8,1992.0
4867,A.J. Guyton,PG,22,CHI,33,8,19.1,2.4,5.8,.406,...,0.3,0.8,1.1,1.9,0.3,0.2,0.7,1.1,6.0,2001.0
5421,A.J. Guyton,PG,23,CHI,45,6,13.5,2.0,5.4,.361,...,0.3,0.7,1.0,1.8,0.2,0.2,0.8,0.5,5.4,2002.0
5929,A.J. Guyton,PG,24,GSW,2,0,4.5,0.0,2.0,.000,...,0.0,0.0,0.0,1.0,0.5,0.0,0.5,0.0,0.0,2003.0
14364,A.J. Hammons,C,24,DAL,22,0,7.4,0.8,1.9,.405,...,0.4,1.3,1.6,0.2,0.0,0.6,0.5,1.0,2.2,2017.0
10270,A.J. Price,PG,23,IND,56,2,15.4,2.6,6.3,.410,...,0.2,1.4,1.6,1.9,0.6,0.1,1.1,0.9,7.3,2010.0
10900,A.J. Price,PG,24,IND,50,0,15.9,2.3,6.4,.356,...,0.3,1.1,1.4,2.2,0.6,0.0,1.1,1.2,6.5,2011.0
11485,A.J. Price,PG,25,IND,44,1,12.9,1.3,4.0,.339,...,0.3,1.1,1.4,2.0,0.5,0.0,0.7,0.7,3.9,2012.0
12078,A.J. Price,PG,26,WAS,57,22,22.4,2.8,7.2,.390,...,0.4,1.6,2.0,3.6,0.6,0.1,1.1,1.3,7.7,2013.0

In [407]:
players.groupby(['Player', 'Year'])

In [320]:
def single_row(df):
    if df.shape[0] == 1:
        return df
    else:
        row = df[df['Tm'] == 'TOT']
        row["Tm"] = df.iloc[-1:]["Tm"]
        return row


players = players.groupby(['Player', 'Year']).apply(single_row)

In [323]:
players.head(50)

                                     Player Pos Age   Tm   G  GS    MP   FG  \
Player         Year
A.C. Green     1992.0 165        A.C. Green  PF  27  LAL  82  21  26.4  3.1
               1993.0 618        A.C. Green  PF  29  LAL  82  55  34.4  4.6
               1994.0 1106       A.C. Green  PF  30  PHO  82  55  34.5  5.7
               1995.0 1595       A.C. Green  SF  31  PHO  82  52  32.8  3.8
               1996.0 2092       A.C. Green  SF  32  PHO  82  36  25.8  2.6
               1997.0 2668       A.C. Green  PF  33  NaN  83  73  30.0  2.8
               1998.0 3256       A.C. Green  PF  34  DAL  82  68  32.3  3.0
               1999.0 3815       A.C. Green  PF  35  DAL  50  35  18.5  2.2
               2000.0 4344       A.C. Green  PF  36  LAL  82  82  23.5  2.1
               2001.0 4864       A.C. Green  PF  37  MIA  82   1  17.2  1.8
A.J. Bramlett  2000.0 4217    A.J. Bramlett   C  23  CLE   8   0   7.6  0.5
A.J. English   1992.0 128      A.J. English  SG  23  WSB  70  12  20.6  3.6
A.J. Guyton    2001.0 4867      A.J. Guyton  PG  22  CHI  33   8  19.1  2.4
               2002.0 5421      A.J. Guyton  PG  23  CHI  45   6  13.5  2.0
               2003.0 5929      A.J. Guyton  PG  24  GSW   2   0   4.5  0.0
A.J. Hammons   2017.0 14364    A.J. Hammons   C  24  DAL  22   0   7.4  0.8
A.J. Price     2010.0 10270      A.J. Price  PG  23  IND  56   2  15.4  2.6
               2011.0 10900      A.J. Price  PG  24  IND  50   0  15.9  2.3
               2012.0 11485      A.J. Price  PG  25  IND  44   1  12.9  1.3
               2013.0 12078      A.J. Price  PG  26  WAS  57  22  22.4  2.8
               2014.0 12709      A.J. Price  SG  27  MIN  28   0   3.5  0.7
               2015.0 13358      A.J. Price  PG  28  NaN  26   0  12.5  2.0
A.J. Wynder    1992.0 458       A.J. Wynder  PG  26  BOS   6   0   6.5  0.5
Aaron Brooks   2008.0 8672     Aaron Brooks  PG  23  HOU  51   0  11.9  1.8
               2009.0 9294     Aaron Brooks  PG  24  HOU  80  35  25.0  4.0
               2010.0 9896     Aaron Brooks  PG  25  HOU  82  82  35.6  7.0
               2011.0 10513    Aaron Brooks  PG  26  NaN  59  12  21.8  3.7
               2013.0 11714    Aaron Brooks  PG  28  NaN  53  20  18.8  2.7
               2014.0 12323    Aaron Brooks  PG  29  NaN  72  12  21.6  3.2
               2015.0 12948    Aaron Brooks  PG  30  CHI  82  21  23.0  4.2
               2016.0 13614    Aaron Brooks  PG  31  CHI  69   0  16.1  2.7
               2017.0 14218    Aaron Brooks  PG  32  IND  65   0  13.8  1.9
               2018.0 14848    Aaron Brooks  PG  33  MIN  32   1   5.9  0.9
Aaron Gordon   2015.0 13102    Aaron Gordon  PF  19  ORL  47   8  17.0  2.0
               2016.0 13735    Aaron Gordon  PF  20  ORL  78  37  23.9  3.5
               2017.0 14348    Aaron Gordon  SF  21  ORL  80  72  28.7  4.9
               2018.0 14990    Aaron Gordon  PF  22  ORL  58  57  32.9  6.5
               2019.0 15714    Aaron Gordon  PF  23  ORL  78  78  33.8  6.0
               2020.0 16430    Aaron Gordon  PF  24  ORL  62  62  32.5  5.4
               2021.0 17107    Aaron Gordon  PF  25  NaN  50  50  27.7  4.6
               2022.0 17867    Aaron Gordon  PF  26  DEN  75  75  31.7  5.8
Aaron Gray     2008.0 8812       Aaron Gray   C  23  CHI  61   1  10.0  1.7
               2009.0 9434       Aaron Gray   C  24  CHI  56  18  12.8  1.4
               2010.0 10025      Aaron Gray   C  25  NaN  32   0   9.7  1.3
               2011.0 10677      Aaron Gray   C  26  NOH  41   6  13.0  1.4
               2012.0 11275      Aaron Gray   C  27  TOR  49  40  16.6  1.7
               2013.0 11841      Aaron Gray   C  28  TOR  42  16  12.2  1.1
               2014.0 12478      Aaron Gray   C  29  NaN  37   6   9.6  0.7
Aaron Harrison 2016.0 13771  Aaron Harrison  SG  21  CHO  21   0   4.4  0.2
               2017.0 14376  Aaron Harrison  SG  22  CHO   5   0   3.4  0.0

                              FGA   FG%  ...  ORB  DRB  TRB  AST  STL  BLK  \
Player         Year                      ...
A.C. Green     1992.0 165     6.6  .476  ...  2.5  3.8  6.3  0.9  0.7  0.3
               1993.0 618     8.6  .537  ...  3.5  5.2  8.7  1.4  1.1  0.5
               1994.0 1106   11.3  .502  ...  3.4  5.8  9.2  1.7  0.9  0.5
               1995.0 1595    7.5  .504  ...  2.4  5.8  8.2  1.5  0.7  0.4
               1996.0 2092    5.4  .484  ...  2.0  4.7  6.8  0.9  0.5  0.3
               1997.0 2668    5.8  .483  ...  2.7  5.2  7.9  0.8  0.8  0.2
               1998.0 3256    6.5  .453  ...  2.7  5.5  8.1  1.5  1.0  0.3
               1999.0 3815    5.1  .422  ...  1.6  2.9  4.6  0.5  0.6  0.2
               2000.0 4344    4.7  .447  ...  2.0  4.0  5.9  1.0  0.6  0.2
               2001.0 4864    4.0  .444  ...  1.3  2.5  3.8  0.5  0.4  0.1
A.J. Bramlett  2000.0 4217    2.6  .190  ...  1.5  1.3  2.8  0.0  0.1  0.0
A.J. English   1992.0 128     8.2  .439  ...  0.9  1.2  2.1  2.5  0.4  0.2
A.J. Guyton    2001.0 4867    5.8  .406  ...  0.3  0.8  1.1  1.9  0.3  0.2
               2002.0 5421    5.4  .361  ...  0.3  0.7  1.0  1.8  0.2  0.2
               2003.0 5929    2.0  .000  ...  0.0  0.0  0.0  1.0  0.5  0.0
A.J. Hammons   2017.0 14364   1.9  .405  ...  0.4  1.3  1.6  0.2  0.0  0.6
A.J. Price     2010.0 10270   6.3  .410  ...  0.2  1.4  1.6  1.9  0.6  0.1
               2011.0 10900   6.4  .356  ...  0.3  1.1  1.4  2.2  0.6  0.0
               2012.0 11485   4.0  .339  ...  0.3  1.1  1.4  2.0  0.5  0.0
               2013.0 12078   7.2  .390  ...  0.4  1.6  2.0  3.6  0.6  0.1
               2014.0 12709   1.6  .413  ...  0.0  0.3  0.4  0.5  0.0  0.0
               2015.0 13358   5.3  .372  ...  0.2  1.0  1.2  1.8  0.3  0.0
A.J. Wynder    1992.0 458     2.0  .250  ...  0.2  0.3  0.5  1.3  0.2  0.0
Aaron Brooks   2008.0 8672    4.4  .413  ...  0.3  0.8  1.1  1.7  0.3  0.1
               2009.0 9294    9.8  .404  ...  0.4  1.6  2.0  3.0  0.6  0.1
               2010.0 9896   16.2  .432  ...  0.7  2.0  2.6  5.3  0.8  0.2
               2011.0 10513   9.9  .375  ...  0.3  1.0  1.3  3.9  0.6  0.1
               2013.0 11714   6.0  .453  ...  0.2  1.3  1.5  2.2  0.6  0.2
               2014.0 12323   8.1  .401  ...  0.6  1.3  1.9  3.2  0.7  0.2
               2015.0 12948  10.0  .421  ...  0.4  1.6  2.0  3.2  0.7  0.2
               2016.0 13614   6.8  .401  ...  0.3  1.2  1.5  2.6  0.4  0.1
               2017.0 14218   4.6  .403  ...  0.3  0.8  1.1  1.9  0.4  0.1
               2018.0 14848   2.2  .406  ...  0.2  0.3  0.5  0.6  0.2  0.0
Aaron Gordon   2015.0 13102   4.4  .447  ...  1.0  2.6  3.6  0.7  0.4  0.5
               2016.0 13735   7.4  .473  ...  2.0  4.5  6.5  1.6  0.8  0.7
               2017.0 14348  10.8  .454  ...  1.5  3.6  5.1  1.9  0.8  0.5
               2018.0 14990  14.9  .434  ...  1.5  6.4  7.9  2.3  1.0  0.8
               2019.0 15714  13.4  .449  ...  1.7  5.7  7.4  3.7  0.7  0.7
               2020.0 16430  12.4  .437  ...  1.7  5.9  7.7  3.7  0.8  0.6
               2021.0 17107  10.0  .463  ...  1.5  4.1  5.7  3.2  0.7  0.7
               2022.0 17867  11.1  .520  ...  1.7  4.2  5.9  2.5  0.6  0.6
Aaron Gray     2008.0 8812    3.3  .505  ...  1.1  1.6  2.8  0.7  0.3  0.3
               2009.0 9434    3.0  .485  ...  1.5  2.4  3.9  0.8  0.3  0.3
               2010.0 10025   2.6  .512  ...  1.4  1.9  3.3  0.7  0.3  0.3
               2011.0 10677   2.4  .566  ...  1.4  2.7  4.2  0.4  0.3  0.3
               2012.0 11275   3.3  .516  ...  1.7  4.0  5.7  0.6  0.4  0.3
               2013.0 11841   2.1  .533  ...  1.1  2.0  3.2  0.8  0.2  0.1
               2014.0 12478   1.6  .443  ...  1.1  1.9  3.0  0.6  0.3  0.2
Aaron Harrison 2016.0 13771   0.9  .263  ...  0.2  0.5  0.7  0.1  0.3  0.0
               2017.0 14376   0.8  .000  ...  0.0  0.6  0.6  0.6  0.0  0.0

                             TOV   PF   PTS    Year
Player         Year
A.C. Green     1992.0 165    1.2  1.4   9.1  1992.0
               1993.0 618    1.4  1.8  12.8  1993.0
               1994.0 1106   1.2  1.7  14.7  1994.0
               1995.0 1595   1.4  1.8  11.2  1995.0
               1996.0 2092   1.0  1.7   7.5  1996.0
               1997.0 2668   0.9  1.7   7.2  1997.0
               1998.0 3256   0.8  1.9   7.3  1998.0
               1999.0 3815   0.4  1.4   4.9  1999.0
               2000.0 4344   0.6  1.5   5.0  2000.0
               2001.0 4864   0.5  1.5   4.5  2001.0
A.J. Bramlett  2000.0 4217   0.4  1.6   1.0  2000.0
A.J. English   1992.0 128    1.6  1.8   8.8  1992.0
A.J. Guyton    2001.0 4867   0.7  1.1   6.0  2001.0
               2002.0 5421   0.8  0.5   5.4  2002.0
               2003.0 5929   0.5  0.0   0.0  2003.0
A.J. Hammons   2017.0 14364  0.5  1.0   2.2  2017.0
A.J. Price     2010.0 10270  1.1  0.9   7.3  2010.0
               2011.0 10900  1.1  1.2   6.5  2011.0
               2012.0 11485  0.7  0.7   3.9  2012.0
               2013.0 12078  1.1  1.3   7.7  2013.0
               2014.0 12709  0.3  0.2   1.6  2014.0
               2015.0 13358  0.5  0.6   5.1  2015.0
A.J. Wynder    1992.0 458    0.7  0.2   2.0  1992.0
Aaron Brooks   2008.0 8672   0.9  1.4   5.2  2008.0
               2009.0 9294   1.6  1.9  11.2  2009.0
               2010.0 9896   2.8  2.4  19.6  2010.0
               2011.0 10513  1.7  1.9  10.7  2011.0
               2013.0 11714  1.3  1.8   7.1  2013.0
               2014.0 12323  1.6  2.0   9.0  2014.0
               2015.0 12948  1.9  2.3  11.6  2015.0
               2016.0 13614  1.2  1.9   7.1  2016.0
               2017.0 14218  1.0  1.4   5.0  2017.0
               2018.0 14848  0.3  0.9   2.3  2018.0
Aaron Gordon   2015.0 13102  0.8  1.8   5.2  2015.0
               2016.0 13735  0.8  2.0   9.2  2016.0
               2017.0 14348  1.1  2.2  12.7  2017.0
               2018.0 14990  1.8  1.9  17.6  2018.0
               2019.0 15714  2.1  2.2  16.0  2019.0
               2020.0 16430  1.6  2.0  14.4  2020.0
               2021.0 17107  1.9  1.8  12.4  2021.0
               2022.0 17867  1.8  2.0  15.0  2022.0
Aaron Gray     2008.0 8812   0.9  1.9   4.3  2008.0
               2009.0 9434   0.7  2.4   3.5  2009.0
               2010.0 10025  0.6  1.7   3.3  2010.0
               2011.0 10677  0.8  2.3   3.1  2011.0
               2012.0 11275  1.0  2.6   3.9  2012.0
               2013.0 11841  0.9  2.0   2.8  2013.0
               2014.0 12478  0.8  1.7   1.8  2014.0
Aaron Harrison 2016.0 13771  0.2  0.5   0.9  2016.0
               2017.0 14376  0.0  0.4   0.2  2017.0

[50 rows x 30 columns]

In [324]:
players.index = players.index.droplevel()

In [325]:
players.index = players.index.droplevel()

In [405]:
#some players are without teams. seems wrong but we will work with it 
players.apply(pd.isna).sum()

Player       0
Pos          0
Age          0
Tm        1650
G            0
GS           0
MP           0
FG           0
FGA          0
FG%         54
3P           0
3PA          0
3P%       2025
2P           0
2PA          0
2P%         95
eFG%        54
FT           0
FTA          0
FT%        509
ORB          0
DRB          0
TRB          0
AST          0
STL          0
BLK          0
TOV          0
PF           0
PTS          0
Year         0
dtype: int64

In [363]:
all_stats = players.merge(mvp, how="outer", on = ["Player", "Year"])

In [367]:
all_stats[["Pts Won", "Pts Max", "Share"]] = all_stats[["Pts Won", "Pts Max", "Share"]].fillna(0)

In [413]:
#The empty teams will lead to inconsistency during the machine learning process
#Drop the rows with Teams empty
all_stats.apply(pd.isna).sum()
all_stats = all_stats.drop(all_stats[pd.isna(all_stats["Tm"])].index)

In [ ]:
#Reshaping the index
all_stats.index = range(all_stats.shape[0])
all_stats.isna().sum()


all_stats["FG%", "3P%", "FT%"] = all_stats["FG%", "3P%", "FT%"].fillna(0)  #columns are still objects

In [ ]:
all_stats.dtypes

In [286]:
teams = pd.read_csv("teams.csv")

In [287]:
teams.head(20)

,Unnamed: 0,W,L,W/L%,GB,PS/G,PA/G,SRS,Year,Team
0,0,56,26,.683,—,111.5,105.7,5.22,1991,Boston Celtics*
1,1,44,38,.537,12.0,105.4,105.6,-0.39,1991,Philadelphia 76ers*
2,2,39,43,.476,17.0,103.1,103.3,-0.43,1991,New York Knicks*
3,3,30,52,.366,26.0,101.4,106.4,-4.84,1991,Washington Bullets
4,4,26,56,.317,30.0,102.9,107.5,-4.53,1991,New Jersey Nets
5,5,24,58,.293,32.0,101.8,107.8,-5.91,1991,Miami Heat
6,6,Central Division,Central Division,Central Division,Central Division,Central Division,Central Division,Central Division,1991,Central Division
7,7,61,21,.744,—,110.0,101.0,8.57,1991,Chicago Bulls*
8,8,50,32,.610,11.0,100.1,96.8,3.08,1991,Detroit Pistons*
9,9,48,34,.585,13.0,106.4,104.0,2.33,1991,Milwaukee Bucks*
10,10,43,39,.524,18.0,109.8,109.0,0.72,1991,Atlanta Hawks*
11,11,41,41,.500,20.0,111.7,112.1,-0.37,1991,Indiana Pacers*
12,12,33,49,.402,28.0,101.7,104.2,-2.33,1991,Cleveland Cavaliers
13,13,26,56,.317,35.0,102.8,108.0,-4.95,1991,Charlotte Hornets
14,0,Midwest Division,Midwest Division,Midwest Division,Midwest Division,Midwest Division,Midwest Division,Midwest Division,1991,Midwest Division
15,1,55,27,.671,—,107.1,102.6,4.30,1991,San Antonio Spurs*
16,2,54,28,.659,1.0,104.0,100.7,3.18,1991,Utah Jazz*
17,3,52,30,.634,3.0,106.7,103.2,3.27,1991,Houston Rockets*
18,4,31,51,.378,24.0,105.9,109.9,-3.79,1991,Orlando Magic
19,5,29,53,.354,26.0,99.6,103.5,-3.75,1991,Minnesota Timberwolves

In [288]:
teams = teams[~teams["W"].str.contains("Division")]
teams.head(20)

,Unnamed: 0,W,L,W/L%,GB,PS/G,PA/G,SRS,Year,Team
0,0,56,26,.683,—,111.5,105.7,5.22,1991,Boston Celtics*
1,1,44,38,.537,12.0,105.4,105.6,-0.39,1991,Philadelphia 76ers*
2,2,39,43,.476,17.0,103.1,103.3,-0.43,1991,New York Knicks*
3,3,30,52,.366,26.0,101.4,106.4,-4.84,1991,Washington Bullets
4,4,26,56,.317,30.0,102.9,107.5,-4.53,1991,New Jersey Nets
5,5,24,58,.293,32.0,101.8,107.8,-5.91,1991,Miami Heat
7,7,61,21,.744,—,110.0,101.0,8.57,1991,Chicago Bulls*
8,8,50,32,.610,11.0,100.1,96.8,3.08,1991,Detroit Pistons*
9,9,48,34,.585,13.0,106.4,104.0,2.33,1991,Milwaukee Bucks*
10,10,43,39,.524,18.0,109.8,109.0,0.72,1991,Atlanta Hawks*
11,11,41,41,.500,20.0,111.7,112.1,-0.37,1991,Indiana Pacers*
12,12,33,49,.402,28.0,101.7,104.2,-2.33,1991,Cleveland Cavaliers
13,13,26,56,.317,35.0,102.8,108.0,-4.95,1991,Charlotte Hornets
15,1,55,27,.671,—,107.1,102.6,4.30,1991,San Antonio Spurs*
16,2,54,28,.659,1.0,104.0,100.7,3.18,1991,Utah Jazz*
17,3,52,30,.634,3.0,106.7,103.2,3.27,1991,Houston Rockets*
18,4,31,51,.378,24.0,105.9,109.9,-3.79,1991,Orlando Magic
19,5,29,53,.354,26.0,99.6,103.5,-3.75,1991,Minnesota Timberwolves
20,6,28,54,.341,27.0,99.9,104.5,-4.27,1991,Dallas Mavericks
21,7,20,62,.244,35.0,119.9,130.8,-10.31,1991,Denver Nuggets

In [289]:
teams["Team"] = teams["Team"].str.replace("*", "", regex=False)

In [291]:
teams.replace("—", "0")

,Unnamed: 0,W,L,W/L%,GB,PS/G,PA/G,SRS,Year,Team
0,0,56,26,.683,0,111.5,105.7,5.22,1991,Boston Celtics
1,1,44,38,.537,12.0,105.4,105.6,-0.39,1991,Philadelphia 76ers
2,2,39,43,.476,17.0,103.1,103.3,-0.43,1991,New York Knicks
3,3,30,52,.366,26.0,101.4,106.4,-4.84,1991,Washington Bullets
4,4,26,56,.317,30.0,102.9,107.5,-4.53,1991,New Jersey Nets
...,...,...,...,...,...,...,...,...,...,...
1063,13,56,26,.683,0,115.6,109.9,5.37,2022,Memphis Grizzlies
1064,14,52,30,.634,4.0,108.0,104.7,3.12,2022,Dallas Mavericks
1065,15,36,46,.439,20.0,109.3,110.3,-0.84,2022,New Orleans Pelicans
1066,16,34,48,.415,22.0,113.2,113.0,0.02,2022,San Antonio Spurs
1067,17,20,62,.244,36.0,109.7,118.2,-8.26,2022,Houston Rockets

In [372]:
teams = teams.drop(teams[teams["Year"] == 1991].index)
teams

       W   L  W/L%    GB   PS/G   PA/G    SRS  Year                  Team
30    51  31  .622     0  106.6  103.0   3.41  1992        Boston Celtics
31    51  31  .622     0  101.6   97.7   3.67  1992       New York Knicks
32    40  42  .488  11.0  105.4  107.1  -1.54  1992       New Jersey Nets
33    38  44  .463  13.0  105.0  109.2  -3.94  1992            Miami Heat
34    35  47  .427  16.0  101.9  103.2  -1.34  1992    Philadelphia 76ers
...   ..  ..   ...   ...    ...    ...    ...   ...                   ...
1063  56  26  .683     0  115.6  109.9   5.37  2022     Memphis Grizzlies
1064  52  30  .634   4.0  108.0  104.7   3.12  2022      Dallas Mavericks
1065  36  46  .439  20.0  109.3  110.3  -0.84  2022  New Orleans Pelicans
1066  34  48  .415  22.0  113.2  113.0   0.02  2022     San Antonio Spurs
1067  20  62  .244  36.0  109.7  118.2  -8.26  2022       Houston Rockets

[909 rows x 9 columns]

In [373]:
teams = teams.replace("—", "0")

In [ ]:
del teams["Unnamed: 0"]

In [429]:
teams

       W   L  W/L%    GB   PS/G   PA/G    SRS  Year                  Team
30    51  31  .622     0  106.6  103.0   3.41  1992        Boston Celtics
31    51  31  .622     0  101.6   97.7   3.67  1992       New York Knicks
32    40  42  .488  11.0  105.4  107.1  -1.54  1992       New Jersey Nets
33    38  44  .463  13.0  105.0  109.2  -3.94  1992            Miami Heat
34    35  47  .427  16.0  101.9  103.2  -1.34  1992    Philadelphia 76ers
...   ..  ..   ...   ...    ...    ...    ...   ...                   ...
1063  56  26  .683     0  115.6  109.9   5.37  2022     Memphis Grizzlies
1064  52  30  .634   4.0  108.0  104.7   3.12  2022      Dallas Mavericks
1065  36  46  .439  20.0  109.3  110.3  -0.84  2022  New Orleans Pelicans
1066  34  48  .415  22.0  113.2  113.0   0.02  2022     San Antonio Spurs
1067  20  62  .244  36.0  109.7  118.2  -8.26  2022       Houston Rockets

[909 rows x 9 columns]

In [ ]:
spec = teams["Team"].unique()
spec

In [ ]:
spec_2 = all_stats["Tm"].unique()
spec_2

In [430]:
all_stats

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,STL,BLK,TOV,PF,PTS,Year,Pts Won,Pts Max,Share,Team
0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,.476,...,0.7,0.3,1.2,1.4,9.1,1992.0,0.0,0.0,0.0,Los Angeles Lakers
1,A.C. Green,PF,29,LAL,82,55,34.4,4.6,8.6,.537,...,1.1,0.5,1.4,1.8,12.8,1993.0,0.0,0.0,0.0,Los Angeles Lakers
2,A.C. Green,PF,30,PHO,82,55,34.5,5.7,11.3,.502,...,0.9,0.5,1.2,1.7,14.7,1994.0,0.0,0.0,0.0,Pheonix Suns
3,A.C. Green,SF,31,PHO,82,52,32.8,3.8,7.5,.504,...,0.7,0.4,1.4,1.8,11.2,1995.0,0.0,0.0,0.0,Pheonix Suns
4,A.C. Green,SF,32,PHO,82,36,25.8,2.6,5.4,.484,...,0.5,0.3,1.0,1.7,7.5,1996.0,0.0,0.0,0.0,Pheonix Suns
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12656,Žarko Čabarkapa,PF,24,GSW,61,0,8.3,1.1,2.9,.385,...,0.2,0.1,0.6,1.4,3.3,2006.0,0.0,0.0,0.0,Golden State Warriors
12657,Željko Rebrača,C,29,DET,74,4,15.9,2.6,5.1,.505,...,0.4,1.0,1.1,2.6,6.9,2002.0,0.0,0.0,0.0,Detroit Pistons
12658,Željko Rebrača,C,30,DET,30,12,16.3,2.7,4.8,.552,...,0.2,0.6,1.0,2.6,6.6,2003.0,0.0,0.0,0.0,Detroit Pistons
12659,Željko Rebrača,C,32,LAC,58,2,16.0,2.3,4.0,.568,...,0.2,0.7,0.8,2.2,5.8,2005.0,0.0,0.0,0.0,Los Angeles Clippers
12660,Željko Rebrača,C,33,LAC,29,2,14.2,1.8,3.3,.542,...,0.2,0.7,0.8,2.0,4.7,2006.0,0.0,0.0,0.0,Los Angeles Clippers

In [431]:
nicknames = {}

with open("nicknames.csv") as f:
    lines = f.readlines()
    for line in lines[1:]:
        name, abbrev = line.replace("\n", "").split(",")
        nicknames[abbrev] = name

In [ ]:
all_stats["Team"] = all_stats["Tm"].map(nicknames)
all_stats[all_stats["Tm"] == "CHA"]

In [433]:
combined_nba_stat = all_stats.merge(teams, how="outer", on = ["Team", "Year"])

In [434]:
combined_nba_stat.apply(pd.isnull).sum()

Player       43
Pos          43
Age          43
Tm           43
G            43
GS           43
MP           43
FG           43
FGA          43
FG%          97
3P           43
3PA          43
3P%        1847
2P           43
2PA          43
2P%         137
eFG%         97
FT           43
FTA          43
FT%         515
ORB          43
DRB          43
TRB          43
AST          43
STL          43
BLK          43
TOV          43
PF           43
PTS          43
Year          0
Pts Won      43
Pts Max      43
Share        43
Team          0
W           607
L           607
W/L%        607
GB          607
PS/G        607
PA/G        607
SRS         607
dtype: int64

In [435]:
#drop rows where the players are empty
combined_nba_stat= combined_nba_stat.drop(combined_nba_stat[pd.isna(combined_nba_stat["Player"])].index)

In [436]:
combined_nba_stat

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,Pts Max,Share,Team,W,L,W/L%,GB,PS/G,PA/G,SRS
0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,.476,...,0.0,0.0,Los Angeles Lakers,43,39,.524,14.0,100.4,101.5,-0.95
1,Byron Scott,SG,29,LAL,82,82,32.1,6.1,12.8,.477,...,0.0,0.0,Los Angeles Lakers,43,39,.524,14.0,100.4,101.5,-0.95
2,Elden Campbell,PF,22,LAL,52,0,7.3,1.1,2.4,.455,...,0.0,0.0,Los Angeles Lakers,43,39,.524,14.0,100.4,101.5,-0.95
3,Irving Thomas,PF,25,LAL,26,0,4.2,0.7,1.9,.340,...,0.0,0.0,Los Angeles Lakers,43,39,.524,14.0,100.4,101.5,-0.95
4,James Worthy,SF,29,LAL,78,74,38.6,9.2,18.7,.492,...,0.0,0.0,Los Angeles Lakers,43,39,.524,14.0,100.4,101.5,-0.95
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12656,Jordan McLaughlin,PG,23,MIN,30,2,19.7,2.9,5.9,.489,...,0.0,0.0,Minnesota Timberwolves,19,45,.297,22.5,113.3,117.5,-4.02
12657,Josh Okogie,SG,21,MIN,62,28,25.0,2.7,6.4,.427,...,0.0,0.0,Minnesota Timberwolves,19,45,.297,22.5,113.3,117.5,-4.02
12658,Karl-Anthony Towns,C,24,MIN,35,35,33.9,9.0,17.8,.508,...,0.0,0.0,Minnesota Timberwolves,19,45,.297,22.5,113.3,117.5,-4.02
12659,Kelan Martin,SF,24,MIN,31,4,16.0,2.3,5.8,.392,...,0.0,0.0,Minnesota Timberwolves,19,45,.297,22.5,113.3,117.5,-4.02
12660,Naz Reid,C,20,MIN,30,11,16.5,3.3,8.1,.412,...,0.0,0.0,Minnesota Timberwolves,19,45,.297,22.5,113.3,117.5,-4.02

In [441]:
combined_nba_stat.dtypes

Player      object
Pos         object
Age          int64
Tm          object
G            int64
GS           int64
MP         float64
FG         float64
FGA        float64
FG%        float64
3P         float64
3PA        float64
3P%        float64
2P         float64
2PA        float64
2P%        float64
eFG%       float64
FT         float64
FTA        float64
FT%        float64
ORB        float64
DRB        float64
TRB        float64
AST        float64
STL        float64
BLK        float64
TOV        float64
PF         float64
PTS        float64
Year       float64
Pts Won    float64
Pts Max    float64
Share      float64
Team        object
W          float64
L          float64
W/L%       float64
GB         float64
PS/G       float64
PA/G       float64
SRS        float64
dtype: object

In [444]:
combined_nba_stat = combined_nba_stat.apply(pd.to_numeric, errors = "ignore")

In [446]:
combined_nba_stat[["FG%", "3P%", "FT%"]] = combined_nba_stat[["FG%", "3P%", "FT%"]].fillna(0)

In [448]:
combined_nba_stat.isna().sum()

Player       0
Pos          0
Age          0
Tm           0
G            0
GS           0
MP           0
FG           0
FGA          0
FG%          0
3P           0
3PA          0
3P%          0
2P           0
2PA          0
2P%         94
eFG%        54
FT           0
FTA          0
FT%          0
ORB          0
DRB          0
TRB          0
AST          0
STL          0
BLK          0
TOV          0
PF           0
PTS          0
Year         0
Pts Won      0
Pts Max      0
Share        0
Team         0
W          607
L          607
W/L%       607
GB         607
PS/G       607
PA/G       607
SRS        607
dtype: int64

In [449]:
combined_nba_stat= combined_nba_stat.drop(combined_nba_stat[pd.isna(combined_nba_stat["W"])].index)

In [451]:
combined_nba_stat.index = range(combined_nba_stat.shape[0])

In [453]:
combined_nba_stat.to_csv("combined_nba_stats.csv", index=False)

HANDLING NICKNAMES DATA

In [454]:
nicknamess = pd.read_csv("nicknames.csv")

In [455]:
#charlotte hornets(CHA) is wrong 
nicknamess

                 Franchise short
0            Atlanta Hawks   ATL
1           Boston Celtics   BOS
2            Brooklyn Nets   BKN
3        Charlotte Hornets   CHA
4            Chicago Bulls   CHI
5      Cleveland Cavaliers   CLE
6         Dallas Mavericks   DAL
7           Denver Nuggets   DEN
8          Detroit Pistons   DET
9    Golden State Warriors   GSW
10         Houston Rockets   HOU
11          Indiana Pacers   IND
12    Los Angeles Clippers   LAC
13      Los Angeles Lakers   LAL
14       Memphis Grizzlies   MEM
15              Miami Heat   MIA
16         Milwaukee Bucks   MIL
17  Minnesota Timberwolves   MIN
18    New Orleans Pelicans   NOP
19         New York Knicks   NYK
20   Oklahoma City Thunder   OKC
21           Orlando Magic   ORL
22      Philadelphia 76ers   PHI
23            Phoenix Suns   PHX
24  Portland Trail Blazers   POR
25        Sacramento Kings   SAC
26       San Antonio Spurs   SAS
27         Toronto Raptors   TOR
28               Utah Jazz   UTA
29      Washington Wizards   WAS
30           Brookyln Nets   BRK
31       Charlotte Hornets   CHH
32       Charlotte Hornets   CHO
33       Charlotte Bobcats   CHA
34         New Jersey Nets   NJN
35     New Orleans Hornets   NOH
36     Seattle SuperSonics   SEA
37    New Orleans Oklahoma   NOK
38            Pheonix Suns   PHO
39     Vancouver Grizzlies   VAN
40      Washington Bullets   WSB

In [196]:
new_names = pd.DataFrame(
    {'Franchise': ["Brookyln Nets", "Charlotte Hornets", "Charlotte Hornets","Charlotte Bobcats", "New Jersey Nets","New Orleans Hornets","Seattle SuperSonics", "New Orleans Oklahoma","Pheonix Suns", "Vancouver Grizzlies","Washington Bullets"], 
     'short': ["BRK","CHH","CHO", "CHA", "NJN","NOH", "SEA", "NOK", "PHO", "VAN", "WSB"]})

In [ ]:
new_names

In [ ]:
nicknames = pd.concat([nick, new_names], ignore_index=True)
nicknames

In [199]:
nicknames.to_csv("nicknames.csv", index=False)

DEALING WITH NAN AND FILL-NA VALUES

In [463]:
#the row was dropped and carefully added back to the dataframea
nicknamess.drop(nicknamess[nicknamess["short"] == "CHA"].index)

                 Franchise short
0            Atlanta Hawks   ATL
1           Boston Celtics   BOS
2            Brooklyn Nets   BKN
4            Chicago Bulls   CHI
5      Cleveland Cavaliers   CLE
6         Dallas Mavericks   DAL
7           Denver Nuggets   DEN
8          Detroit Pistons   DET
9    Golden State Warriors   GSW
10         Houston Rockets   HOU
11          Indiana Pacers   IND
12    Los Angeles Clippers   LAC
13      Los Angeles Lakers   LAL
14       Memphis Grizzlies   MEM
15              Miami Heat   MIA
16         Milwaukee Bucks   MIL
17  Minnesota Timberwolves   MIN
18    New Orleans Pelicans   NOP
19         New York Knicks   NYK
20   Oklahoma City Thunder   OKC
21           Orlando Magic   ORL
22      Philadelphia 76ers   PHI
23            Phoenix Suns   PHX
24  Portland Trail Blazers   POR
25        Sacramento Kings   SAC
26       San Antonio Spurs   SAS
27         Toronto Raptors   TOR
28               Utah Jazz   UTA
29      Washington Wizards   WAS
30           Brookyln Nets   BRK
31       Charlotte Hornets   CHH
32       Charlotte Hornets   CHO
34         New Jersey Nets   NJN
35     New Orleans Hornets   NOH
36     Seattle SuperSonics   SEA
37    New Orleans Oklahoma   NOK
38            Pheonix Suns   PHO
39     Vancouver Grizzlies   VAN
40      Washington Bullets   WSB

In [466]:
nicknamess['short'].str.slice(stop=3)

0     ATL
1     BOS
2     BKN
3     CHA
4     CHI
5     CLE
6     DAL
7     DEN
8     DET
9     GSW
10    HOU
11    IND
12    LAC
13    LAL
14    MEM
15    MIA
16    MIL
17    MIN
18    NOP
19    NYK
20    OKC
21    ORL
22    PHI
23    PHX
24    POR
25    SAC
26    SAS
27    TOR
28    UTA
29    WAS
30    BRK
31    CHH
32    CHO
33    CHA
34    NJN
35    NOH
36    SEA
37    NOK
38    PHO
39    VAN
40    WSB
Name: short, dtype: object